version: '3.8'

services:
    ai-service:
        build:
            context: ./ai
            dockerfile: Dockerfile
        container_name: ai-microservice
        restart: always
        ports:
            - '4000:4000'
        volumes:
            - ./ai:/app
        env_file:
            - ./ai/.env
        networks:
            - app-network

    api-service:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: golang-api
        restart: always
        ports:
            - '8080:8080'
        volumes:
            - ./backend:/app
        env_file:
            - ./backend/.env
        depends_on:
            - ai-service
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
