name: backend

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Lint Code
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ./backend/
          args: --timeout=5m
  test:
    name: Test Code
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Create .env File
        working-directory: ./backend/
        run: |
          touch .env
          echo ATLAS_URI=${{ secrets.ATLAS_URI }} >> .env
          echo ENVIRONMENT=Dev >> .env
      - name: Test Code
        run: cd backend && go test ./...