name: backend

on:
  push:
    branches:
      - "**"

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Lint Code
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ./backend/
          args: --timeout=5m
  test:
    name: Test Code
    runs-on: ubuntu-latest
    environment: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Create .env File
        run: |
          touch .env
          echo ATLAS_URI=${{ secrets.ATLAS_URI }} >> .env
          echo ENVIRONMENT=Dev >> .env
        with:
          working-directory: backend
      - name: Test Code
        run: cd backend && go test ./...